version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: jwt_security
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  app:
    image: api-skripsi # Replace with your actual Spring Boot app image name
    container_name: api-skripsi
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance-app
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - "8080:8080" # Adjust if your Spring Boot app runs on a different port

volumes:
  postgres-data:
    external: false
